@baseUrl= http://localhost:3001
@adminTenentId=123
@token=123

###

# @name 请求 /login 接口 => 成功 
GET {{baseUrl}}/api/base/login/captcha-image-svg
Content-Type: application/json
 
###

# @name 请求 /login 接口 => 成功 
GET {{baseUrl}}/api/base/login/captcha-image-code
Content-Type: application/json
tenant-id: {{adminTenentId}}

###

# @name 请求 /login 接口 => 成功 
POST {{baseUrl}}/api/base/login
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "username": "admin",
  "password": "123456",
  "codeId": "a3fc0d8d-499e-4417-bbd6-69271f944852",
  "code": "11"
}

###

# @name 请求 /login 接口 => 成功（无验证码)
POST {{baseUrl}}/api/base/login
Content-Type: application/json
tenant-id: {{adminTenentId}}

{
  "username": "admin",
  "password": "admin123",
}

### 

# @name 请求 /login 接口 => 成功（无验证码)
POST {{baseUrl}}/api/base/login/get-info
Content-Type: application/json

### 

# @name 请求 /get-permission-info 接口 => 成功
GET {{baseUrl}}/system/auth/get-permission-info
Authorization: Bearer {{token}}
tenant-id: {{adminTenentId}}

### 

# @name 请求 /list-menus 接口 => 成功
GET {{baseUrl}}/system/list-menus
Authorization: Bearer {{token}}
#Authorization: Bearer a6aa7714a2e44c95aaa8a2c5adc2a67a
tenant-id: {{adminTenentId}}
