import * as z from "zod"

export const OrganizationModelSchema = z.object({
  id: z.string(),
  login: z.string(),
  nodeId: z.string(),
  url: z.string(),
  reposUrl: z.string(),
  eventsUrl: z.string(),
  hooksUrl: z.string(),
  issuesUrl: z.string(),
  membersUrl: z.string(),
  publicMembersUrl: z.string(),
  avatarUrl: z.string(),
  description: z.string(),
  name: z.string(),
  company: z.string(),
  blog: z.string(),
  location: z.string(),
  email: z.string(),
  twitterUsername: z.string(),
  isVerified: z.number().int(),
  hasOrganization_projects: z.number().int(),
  hasRepository_projects: z.number().int(),
  publicRepos: z.number().int(),
  publicGists: z.number().int(),
  followers: z.number().int(),
  following: z.number().int(),
  htmlUrl: z.string(),
  type: z.string(),
  createdAt: z.date().nullish(),
  updatedAt: z.date(),
})
