import * as z from "zod"

export const SelfHeatingBOModelSchema = z.object({
  id: z.string(),
  createdAt: z.date().nullish(),
  updatedAt: z.date(),
  innerCode: z.string(),
  type: z.number().int(),
  code: z.string(),
  outBoxType: z.number().int(),
  innerBoxType: z.number().int(),
  materialType: z.number().int(),
  color: z.number().int(),
  outBoxCapacity: z.number().int(),
  innerBoxCapacity: z.number().int(),
  innerBoxCapacityLine: z.number().int(),
  innerBoxCapacity2: z.number().int(),
  innerBoxCapacity3: z.number().int(),
  innerBoxCapacity4: z.number().int(),
  outBoxSize: z.number().int(),
  innerBoxSize: z.number().int(),
  outBoxSizeX: z.number().int(),
  innerBoxSizeX: z.number().int(),
  outBoxSizeY: z.number().int(),
  innerBoxSizeY: z.number().int(),
  outBoxSizeZ: z.number().int(),
  innerBoxSizeZ: z.number().int(),
  lidWeight: z.number().int(),
  bottomWeight: z.number().int(),
  innerWeight: z.number().int(),
  cost: z.number().int(),
})
