compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com/"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
