packages:
  - 'apps/admin'
  - 'apps/design'
  - 'apps/desktop'
  - 'apps/lab'
  - 'apps/mobile'
  - 'apps/web'
  - 'apps/extension'
  - 'prisma'
  - 'packages/schema'
  - 'packages/utils'
  - 'packages/hooks'
  - 'packages/utils'
  - 'packages/i18n'
  - 'packages/design'
  - 'packages/ui'
  - 'packages/validators'
  - 'services/server'
  - 'tasks/jobs/apple-guide-spider'
  - 'tooling/eslint-config'
  - 'tooling/github-config'
  - 'tooling/prettier-config'
  - 'tooling/tailwind-config'
  - 'tooling/typescript-config'
