packages:
  - 'apps/lab'
  - 'apps/web'
  - 'apps/admin'
  - 'prisma'
  - 'packages/schema'
  - 'packages/utils'
  - 'packages/api-gateway'
  - 'packages/hooks'
  # - 'packages/api'
  # - 'packages/auth'
  # - 'packages/db'
  - 'packages/ui'
  - 'packages/validators'
  - 'tasks/jobs/apple-guide-spider'
  - 'tooling/eslint-config-base'
  - 'tooling/eslint-config'
  - 'tooling/github-config'
  - 'tooling/prettier-config'
  - 'tooling/tailwind-config'
  - 'tooling/typescript-config'
