// sn: DataTypes.STRING,
// checkoutPrice: DataTypes.INTEGER,
// shipping_fee: DataTypes.INTEGER,
// discount_fee: DataTypes.INTEGER,
// total_amount: DataTypes.INTEGER,
// name: DataTypes.STRING,
// email: DataTypes.STRING,
// phone: DataTypes.STRING,
// address: DataTypes.STRING,
// order_status: DataTypes.STRING,
// remark: DataTypes.TEXT,
// shipping_status: DataTypes.STRING,
// payment_status: DataTypes.STRING,
// UserId: DataTypes.INTEGER,
// CouponId: DataTypes.INTEGER,
// DiscountId: DataTypes.INTEGER
export {}
