import '../styles/code-highlight.css'
import '../styles/globals.css'
import '../styles/markdown.css'
import '../styles/quill.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body >{children}</body>
        </html>
    )
}
