import { DemoPage } from '@/features/demo/pages'
import { prisma } from '@/server/db/prisma'
import { trpc } from '@/utils/trpc'
import { useEffect } from 'react'
import { Container } from '@/components/common'
import { signIn, signOut, useSession } from 'next-auth/react'
import Link from 'next/link'
import Head from 'next/head'

const TaskBlock = (props) => {
    return (
        <div className="">
            <h3 className="">最近任务</h3>
            <div className="text-gray-700 bg-white p-5">
                {
                    props.tasks.map(item => (
                        <div key={item.id} className="leading-6 no-underline">
                            <Link href={`/freelancer/task/${item.id}`}>
                                {item.title}
                            </Link>
                        </div>
                    ))
                }
            </div>
        </div>
    );
}

const DemoRoute = (props) => {
    const hello = trpc.example.hello.useQuery({ text: "from tRPC test" });
    const getAll = trpc.example.getAll.useQuery();
    const getSecretMessage = trpc.example.getSecretMessage.useQuery();

    useEffect(() => {
        console.log('post:', props.post)
        console.log('hello: ', hello.data, getAll.data, getSecretMessage.data);

    }, [hello, getAll, getSecretMessage])

    return <DemoPage />;
}

const AuthShowcase = () => {
    const { data: sessionData } = useSession();

    const { data: secretMessage } = trpc.example.getSecretMessage.useQuery(
    )

    return (
        <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl text-white">
                {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
                {secretMessage && <span> - {secretMessage}</span>}
            </p>
            <button
                onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
                {sessionData ? "Sign out" : "Sign in"}
            </button>
        </div>
    )
}

const Index = () => {
    const { data: hello, isLoading } = trpc.example.hello.useQuery({ text: "from tRPC test" });

    return (
        <>
            <Head>
                <title>Lab</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <p className="text-2xl text-white">
                    {hello ? hello.greeting : "Loading tRPC query..."}
                </p>
            </Container>
        </>
    );
}

export default Index

export async function getServerSideProps({ query }: any) {
    const post = await prisma.poem.findMany()

    return {
        props: {
            post,
        },
    }
}
