import { trpc } from '@/utils/trpc'
import { Container } from '@/components/common'
import { signIn, signOut, useSession } from 'next-auth/react'
import Link from 'next/link'
import Head from 'next/head'
import type { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import { getServerTranslations } from '@/server/backend/i18n/getServerTranslations'
import { homeConfig } from '@/features/HomePage/home.config'
import { HomePage } from '@/features/HomePage/pages'

type Props = {}

const Index = (
  _props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  const { data: session } = useSession()

  console.log('session: ', session)

  // const { data: hello, isLoading } = trpc.example.hello.useQuery({
  //   text: 'from tRPC',
  // })
  // const { data: secretMessage } = trpc.example.getSecretMessage.useQuery()

  // const { data: links = [] } = trpc.link.getLinks.useQuery()

  // console.log('links: ', links)

  console.log('session: ', session)
  return (
    <>
      <Head>
        <title>Lab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  )
}

export default Index

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const { locale = 'en' } = context

  if (locale === undefined) {
    throw new Error('locale is missing')
  }
  const { i18nNamespaces } = homeConfig
  return {
    props: {
      ...(await getServerTranslations(locale, i18nNamespaces)),
    },
  }
}
