import { Container } from '@/components/common';
import { getRencentTasks } from '@/server/task';
// import { useAppSelector } from '@/stores/hooks';
// import { useTranslation } from 'next-i18next';
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";
import { trpc } from "@/utils/trpc";
// import { Footer } from '@/components/layouts/components/BaseLayout/Footer'
import { type NextPage } from 'next';
import { ColorSchemeToggle } from '@/components/ui/ColorSchemeToggle';
import Head from "next/head";
import { prisma } from '@/lib/prisma';

const TaskBlock = (props) => {
  return (
    <div className="">
      <h3 className="">最近任务</h3>
      <div className="text-gray-700 bg-white p-5">
        {
          props.tasks.map(item => (
            <div key={item.id} className="leading-6 no-underline">
              <Link href={`/freelancer/task/${item.id}`}>
                {/* {new Date(item.time)} {item.title} */}
                {
                  // format(new Date(item.time), 'MM-dd HH:mm')
                }
                {item.title}
              </Link>
            </div>
          ))
        }
      </div>
    </div>
  );
}

const Home: NextPage = (props) => {
  // const { t } = useTranslation();

  // const user = useAppSelector((state) => state.auth.user);
  // const isLoggedIn = useAppSelector((state) => state.auth.isLoggedIn);

  const hello = trpc.example.hello.useQuery({ text: "from tRPC test" });
  const getAll = trpc.example.getAll.useQuery();
  const getSecretMessage = trpc.example.getSecretMessage.useQuery();

  console.log('posts: ', props.posts)


  // const email = user?.email || '';
  // const { tasks } = props;

  console.log('hello: ', hello, getAll, getSecretMessage);

  return (
    <>
      <Head>
        <title>Lab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ColorSchemeToggle />
        <p className="text-2xl text-white">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>
        {/* <AuthShowcase /> */}
      </Container>
      {/* <Footer /> */}
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const posts = await prisma.post.findMany()

  console.log('posts: ', posts)

  return { props: { posts } }
}

// export async function getServerSideProps({ query }: any) {
//   // const res = await getRencentTasks();
//   // console.log('res: ', res);
//   return {
//     props: {
//       // tasks: res.data,
//     },
//   };
// }

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
