/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsSubscribedRouteImport } from './routes/tools-subscribed'
import { Route as ToolsSubscribeRouteImport } from './routes/tools-subscribe'
import { Route as ToolsIntroRouteImport } from './routes/tools-intro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'

const ToolsSubscribedRoute = ToolsSubscribedRouteImport.update({
  id: '/tools-subscribed',
  path: '/tools-subscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSubscribeRoute = ToolsSubscribeRouteImport.update({
  id: '/tools-subscribe',
  path: '/tools-subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIntroRoute = ToolsIntroRouteImport.update({
  id: '/tools-intro',
  path: '/tools-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/tools-intro': typeof ToolsIntroRoute
  '/tools-subscribe': typeof ToolsSubscribeRoute
  '/tools-subscribed': typeof ToolsSubscribedRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/tools-intro': typeof ToolsIntroRoute
  '/tools-subscribe': typeof ToolsSubscribeRoute
  '/tools-subscribed': typeof ToolsSubscribedRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/tools-intro': typeof ToolsIntroRoute
  '/tools-subscribe': typeof ToolsSubscribeRoute
  '/tools-subscribed': typeof ToolsSubscribedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tools-intro' | '/tools-subscribe' | '/tools-subscribed' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/tools-intro' | '/tools-subscribe' | '/tools-subscribed' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/tools-intro'
    | '/tools-subscribe'
    | '/tools-subscribed'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ToolsIntroRoute: typeof ToolsIntroRoute
  ToolsSubscribeRoute: typeof ToolsSubscribeRoute
  ToolsSubscribedRoute: typeof ToolsSubscribedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools-subscribed': {
      id: '/tools-subscribed'
      path: '/tools-subscribed'
      fullPath: '/tools-subscribed'
      preLoaderRoute: typeof ToolsSubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-subscribe': {
      id: '/tools-subscribe'
      path: '/tools-subscribe'
      fullPath: '/tools-subscribe'
      preLoaderRoute: typeof ToolsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-intro': {
      id: '/tools-intro'
      path: '/tools-intro'
      fullPath: '/tools-intro'
      preLoaderRoute: typeof ToolsIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ToolsIntroRoute: ToolsIntroRoute,
  ToolsSubscribeRoute: ToolsSubscribeRoute,
  ToolsSubscribedRoute: ToolsSubscribedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
