name: e2e

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        working-directory: ./packages/lab
        run: npm install

      - name: Wait for preview deployment
        working-directory: ./packages/lab
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        run: node deployment/waitForPreview.js $VERCEL_TOKEN

      - name: Get Deployment URL
        working-directory: ./packages/lab
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        run: echo "CYPRESS_BASE_URL=https://$(node deployment/getDeploymentUrl.js)" >> $GITHUB_ENV

      - name: Run Cypress 🌲
        working-directory: ./packages/lab
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}
        run: CYPRESS_BASE_URL=${CYPRESS_BASE_URL} npm run test 

